/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ibravenda.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrew
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();

        // GUIPrincipal maximizada ao abrir
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneGUIPrincipal = new javax.swing.JDesktopPane();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuPedido = new javax.swing.JMenu();
        jMenuItemPedido = new javax.swing.JMenuItem();
        jMenuItemPedidoProdutoBuscar = new javax.swing.JMenuItem();
        jMenuItemPedidoListar = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenu();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuItemProdutoBuscar = new javax.swing.JMenuItem();
        jMenuVendedor = new javax.swing.JMenu();
        jMenuItemVendedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneGUIPrincipalLayout = new javax.swing.GroupLayout(jDesktopPaneGUIPrincipal);
        jDesktopPaneGUIPrincipal.setLayout(jDesktopPaneGUIPrincipalLayout);
        jDesktopPaneGUIPrincipalLayout.setHorizontalGroup(
            jDesktopPaneGUIPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPaneGUIPrincipalLayout.setVerticalGroup(
            jDesktopPaneGUIPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/cart.png"))); // NOI18N
        jMenuPedido.setText("Pedido");

        jMenuItemPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/add.png"))); // NOI18N
        jMenuItemPedido.setText("Ações");
        jMenuItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemPedido);

        jMenuItemPedidoProdutoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/magnifier.png"))); // NOI18N
        jMenuItemPedidoProdutoBuscar.setText("Buscar");
        jMenuItemPedidoProdutoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoProdutoBuscarActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemPedidoProdutoBuscar);

        jMenuItemPedidoListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/table.png"))); // NOI18N
        jMenuItemPedidoListar.setText("Listar");
        jMenuItemPedidoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoListarActionPerformed(evt);
            }
        });
        jMenuPedido.add(jMenuItemPedidoListar);

        jMenuBarPrincipal.add(jMenuPedido);

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/user.png"))); // NOI18N
        jMenuCliente.setText("Cliente");

        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/add.png"))); // NOI18N
        jMenuItemCliente.setText("Ações");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemCliente);

        jMenuBarPrincipal.add(jMenuCliente);

        jMenuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/brick.png"))); // NOI18N
        jMenuProduto.setText("Produto");

        jMenuItemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/add.png"))); // NOI18N
        jMenuItemProduto.setText("Ações");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuItemProduto);

        jMenuItemProdutoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/magnifier.png"))); // NOI18N
        jMenuItemProdutoBuscar.setText("Buscar");
        jMenuItemProdutoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoBuscarActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuItemProdutoBuscar);

        jMenuBarPrincipal.add(jMenuProduto);

        jMenuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/user_gray.png"))); // NOI18N
        jMenuVendedor.setText("Vendedor");

        jMenuItemVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/add.png"))); // NOI18N
        jMenuItemVendedor.setText("Ações");
        jMenuItemVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendedorActionPerformed(evt);
            }
        });
        jMenuVendedor.add(jMenuItemVendedor);

        jMenuBarPrincipal.add(jMenuVendedor);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneGUIPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneGUIPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
        try {
            GUICliente guiCliente = new GUICliente();
            jDesktopPaneGUIPrincipal.add(guiCliente);
            guiCliente.setVisible(true);
            guiCliente.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoActionPerformed
        // TODO add your handling code here:
        try {
            GUIPedido guiPedido = new GUIPedido();
            jDesktopPaneGUIPrincipal.add(guiPedido);
            guiPedido.setVisible(true);
            guiPedido.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemPedidoActionPerformed

    private void jMenuItemPedidoProdutoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoProdutoBuscarActionPerformed
        // TODO add your handling code here:
        try {
            GUIPedidoProduto guiPedidoProduto = new GUIPedidoProduto();
            jDesktopPaneGUIPrincipal.add(guiPedidoProduto);
            guiPedidoProduto.setVisible(true);
            guiPedidoProduto.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemPedidoProdutoBuscarActionPerformed

    private void jMenuItemPedidoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoListarActionPerformed
        // TODO add your handling code here:
         try {
            GUIPedidoListar guiPedidoListar = new GUIPedidoListar();
            jDesktopPaneGUIPrincipal.add(guiPedidoListar);
            guiPedidoListar.setVisible(true);
            guiPedidoListar.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemPedidoListarActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        // TODO add your handling code here:
        try {
            GUIProduto guiProduto = new GUIProduto();
            jDesktopPaneGUIPrincipal.add(guiProduto);
            guiProduto.setVisible(true);
            guiProduto.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemProdutoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoBuscarActionPerformed
        // TODO add your handling code here:
        try {
            GUIProdutoListar guiProdutoListar = new GUIProdutoListar();
            jDesktopPaneGUIPrincipal.add(guiProdutoListar);
            guiProdutoListar.setVisible(true);
            guiProdutoListar.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemProdutoBuscarActionPerformed

    private void jMenuItemVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendedorActionPerformed
        // TODO add your handling code here:
        try {
            GUIVendedor guiVendedor = new GUIVendedor();
            jDesktopPaneGUIPrincipal.add(guiVendedor);
            guiVendedor.setVisible(true);
            guiVendedor.setPosicao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneGUIPrincipal;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemPedido;
    private javax.swing.JMenuItem jMenuItemPedidoListar;
    private javax.swing.JMenuItem jMenuItemPedidoProdutoBuscar;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemProdutoBuscar;
    private javax.swing.JMenuItem jMenuItemVendedor;
    private javax.swing.JMenu jMenuPedido;
    private javax.swing.JMenu jMenuProduto;
    private javax.swing.JMenu jMenuVendedor;
    // End of variables declaration//GEN-END:variables
}
