/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ibravenda.gui;

import ibravenda.cliente.Cliente;
import ibravenda.fachada.Fachada;
import ibravenda.pedido.Pedido;
import ibravenda.pedidoProduto.PedidoProduto;
import ibravenda.produto.Produto;
import ibravenda.vendedor.Vendedor;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrew
 */
public class GUIPedido extends javax.swing.JInternalFrame {

    ArrayList<PedidoProduto> pedido_produto = new ArrayList<>();
    ArrayList<Produto> produtos;
    ArrayList<Vendedor> vendedores;
    ArrayList<Cliente> clientes;

    /**
     * Creates new form GUIPedido
     */
    public GUIPedido() {
        initComponents();
        popularComboProduto();
        popularComboVendedor();
        popularComboCliente();
    }

    private void carregarTabelaProdutosEscolhidos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Descrição", "Preço", "Quantidade", "Total"});
        for (PedidoProduto pp : pedido_produto) {
            modelo.addRow(new Object[]{
                pp.getProduto().getDescricao(),
                pp.getProduto().getPreco(),
                pp.getQuantidade(),
                String.format("%.2f", pp.getTotal())
            });
        }
        jTableProdutosPedido.setModel(modelo);
        Pedido p = new Pedido();
        p.setProdutos(pedido_produto);
        jLabelTotalInfo.setText("Total: R$ " + String.format("%.2f", p.getTotalPedido()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutosPedido = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        jLabelData = new javax.swing.JLabel();
        jLabelVendedorInfo = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jLabelClienteInfo = new javax.swing.JLabel();
        jLabelProdutoInfo = new javax.swing.JLabel();
        jTextFieldProdutoQuantidade = new javax.swing.JTextField();
        jLabelProdutoQuantidade = new javax.swing.JLabel();
        jComboBoxVendedor = new javax.swing.JComboBox<>();
        jButtonAdicionarProduto = new javax.swing.JButton();
        jLabelVendedor = new javax.swing.JLabel();
        jButtonFinalizar = new javax.swing.JButton();
        jLabelCliente = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabelProduto = new javax.swing.JLabel();
        jLabelTotalInfo = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens "));

        jTableProdutosPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descrição", "Preço", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutosPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutosPedido);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido "));

        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBoxProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxProdutoItemStateChanged(evt);
            }
        });

        jLabelData.setText("Data:");

        jLabelVendedorInfo.setText("CPF:");

        jLabelClienteInfo.setText("CPF:");

        jLabelProdutoInfo.setText("Preço:");

        jTextFieldProdutoQuantidade.setText("1");

        jLabelProdutoQuantidade.setText("Quantidade:");

        jComboBoxVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBoxVendedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxVendedorItemStateChanged(evt);
            }
        });

        jButtonAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/cart_add.png"))); // NOI18N
        jButtonAdicionarProduto.setText("Adicionar produto");
        jButtonAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarProdutoActionPerformed(evt);
            }
        });

        jLabelVendedor.setText("Vendedor:");

        jButtonFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibravenda/imagens/money.png"))); // NOI18N
        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });

        jLabelCliente.setText("Cliente:");

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBoxCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxClienteItemStateChanged(evt);
            }
        });

        jLabelProduto.setText("Produto:");

        jLabelTotalInfo.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVendedor)
                    .addComponent(jLabelCliente)
                    .addComponent(jLabelProduto)
                    .addComponent(jLabelProdutoQuantidade)
                    .addComponent(jLabelData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldProdutoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButtonAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFinalizar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVendedorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelClienteInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProdutoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVendedor)
                    .addComponent(jLabelVendedorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCliente)
                    .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClienteInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProduto)
                    .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProdutoInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProdutoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProdutoQuantidade)
                    .addComponent(jLabelTotalInfo)
                    .addComponent(jButtonAdicionarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFinalizar)
                    .addComponent(jLabelData)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxVendedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxVendedorItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxVendedor.getSelectedIndex() > -1) {
            jLabelVendedorInfo.setText("CPF: " + vendedores.get(jComboBoxVendedor.getSelectedIndex()).getCpf());
        }
    }//GEN-LAST:event_jComboBoxVendedorItemStateChanged

    private void jComboBoxClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxClienteItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxCliente.getSelectedIndex() > -1) {
            jLabelClienteInfo.setText("CPF: " + clientes.get(jComboBoxCliente.getSelectedIndex()).getCpf());
        }

    }//GEN-LAST:event_jComboBoxClienteItemStateChanged

    private void jComboBoxProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxProdutoItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxProduto.getSelectedIndex() > -1) {
            jLabelProdutoInfo.setText("R$" + String.format("%.2f", produtos.get(jComboBoxProduto.getSelectedIndex()).getPreco()));
        }
    }//GEN-LAST:event_jComboBoxProdutoItemStateChanged

    /**
     * Verifica se o produto já está inserido no ArrayList pedido_produto caso
     * esteja atualiza com a nova informação de quantidade
     *
     * @param pp
     * @return boolean
     */
    private boolean encontrarPedidoProduto(PedidoProduto pp) {
        boolean achou = false;
        for (PedidoProduto ppd : pedido_produto) {
            if (ppd.getProduto().getCodigo() == pp.getProduto().getCodigo()) {
                ppd.setQuantidade(Integer.parseInt(jTextFieldProdutoQuantidade.getText()));
                achou = true;
            }
        }
        return achou;
    }

    private void jButtonAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarProdutoActionPerformed
        // TODO add your handling code here:
        if (jTextFieldProdutoQuantidade.getText().trim().equals("") == false) {

            try {
                if (jComboBoxProduto.getSelectedIndex() < 0) {
                    throw new Exception("Informe o produto.");
                }
                Produto prd = new Produto();
                prd.setCodigo(produtos.get(jComboBoxProduto.getSelectedIndex()).getCodigo());

                try {
                    for (int i = 0; i < produtos.size(); i++) {
                        if (produtos.get(i).getCodigo() == prd.getCodigo() && produtos.get(i).getEstoque() < Integer.parseInt(jTextFieldProdutoQuantidade.getText())) {
                            throw new Exception("O estoque do produto é " + produtos.get(i).getEstoque());
                        }
                    }
                    PedidoProduto pp = new PedidoProduto();
                    pp.setProduto(produtos.get(jComboBoxProduto.getSelectedIndex()));
                    pp.setPreco(pp.getProduto().getPreco());
                    if (!encontrarPedidoProduto(pp)) {
                        pp.setQuantidade(Integer.parseInt(jTextFieldProdutoQuantidade.getText()));
                        pedido_produto.add(pp);
                    }
                    jTextFieldProdutoQuantidade.setText("1");
                    carregarTabelaProdutosEscolhidos();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Informe a quantidade!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAdicionarProdutoActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        // TODO add your handling code here:
        Fachada f = new Fachada();
        Pedido p = new Pedido();
        try {
            if (jComboBoxVendedor.getSelectedIndex() < 0) {
                throw new Exception("Informe o vendedor.");
            }
            if (jComboBoxCliente.getSelectedIndex() < 0) {
                throw new Exception("Informe o cliente.");
            }

            p.setData(jTextFieldData.getText());
            p.setVendedor(vendedores.get(jComboBoxVendedor.getSelectedIndex()));
            p.setCliente(clientes.get(jComboBoxCliente.getSelectedIndex()));
            p.setProdutos(pedido_produto);
            f.cadastrar(p);

            JOptionPane.showMessageDialog(null, "Pedido registrado com sucesso.");
            jTextFieldData.setText("");
            pedido_produto = new ArrayList<>();
            jComboBoxVendedor.setSelectedIndex(-1);
            jComboBoxCliente.setSelectedIndex(-1);
            jComboBoxProduto.setSelectedIndex(-1);
            jLabelVendedorInfo.setText("CPF: ");
            jLabelClienteInfo.setText("CPF: ");
            jLabelProdutoInfo.setText("Preço: ");
            carregarTabelaProdutosEscolhidos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    private void jTableProdutosPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosPedidoMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Deseja realmente remover?", "Atenção", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
            pedido_produto.remove(jTableProdutosPedido.getSelectedRow());
            carregarTabelaProdutosEscolhidos();
        }
    }//GEN-LAST:event_jTableProdutosPedidoMouseClicked

    private void popularComboProduto() {
        try {
            Produto filtro = new Produto();
            Fachada f = new Fachada();
            produtos = f.listar(filtro);

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            if (produtos.size() > 0) {
                for (int i = 0; i < produtos.size(); i++) {
                    Produto p = produtos.get(i);
                    modelo.addElement(p.getDescricao());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum produto cadastrado.", "Atenção", JOptionPane.WARNING_MESSAGE);
                jButtonFinalizar.setEnabled(false);
            }

            jComboBoxProduto.setModel(modelo);
            jComboBoxProduto.setSelectedIndex(-1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void popularComboVendedor() {
        try {
            Vendedor filtro = new Vendedor();
            Fachada f = new Fachada();
            vendedores = f.listar(filtro);

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            if (vendedores.size() > 0) {
                for (int i = 0; i < vendedores.size(); i++) {
                    Vendedor v = vendedores.get(i);
                    modelo.addElement(v.getNome());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum vendedor cadastrado.", "Atenção", JOptionPane.WARNING_MESSAGE);
                jButtonFinalizar.setEnabled(false);
            }

            jComboBoxVendedor.setModel(modelo);
            jComboBoxVendedor.setSelectedIndex(-1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void popularComboCliente() {
        try {
            Cliente filtro = new Cliente();
            Fachada f = new Fachada();
            clientes = f.listar(filtro);

            DefaultComboBoxModel modelo = new DefaultComboBoxModel();

            if (clientes.size() > 0) {
                for (int i = 0; i < clientes.size(); i++) {
                    Cliente c = clientes.get(i);
                    modelo.addElement(c.getNome());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum cliente cadastrado.", "Atenção", JOptionPane.WARNING_MESSAGE);
                jButtonFinalizar.setEnabled(false);
            }

            jComboBoxCliente.setModel(modelo);
            jComboBoxCliente.setSelectedIndex(-1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarProduto;
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JComboBox<String> jComboBoxVendedor;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelClienteInfo;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelProdutoInfo;
    private javax.swing.JLabel jLabelProdutoQuantidade;
    private javax.swing.JLabel jLabelTotalInfo;
    private javax.swing.JLabel jLabelVendedor;
    private javax.swing.JLabel jLabelVendedorInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutosPedido;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldProdutoQuantidade;
    // End of variables declaration//GEN-END:variables
}
